[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
restartPolicyType = "always"

[[networking.serviceDomains]]
domain = "<hasDomain>"
port = 8080

[[networking.serviceDomains]]
domain = "<hasDomain>"
port = 8644